apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod2
  labels:
    app: my-app
spec:
  containers:
    - name: my-app-container
      image: nginx
      ports:
        - containerPort: 80
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd