apiVersion: v1
kind: Pod
metadata:
  name: my-nginx3
  labels : 
    app : my-nginx
spec:
  nodeName: mtaks-worker2
  containers:
  - name: nginx
    image: nginx
    ports : 
      - containerPort: 80
